<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.540">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chaohua Li Data Analysis Portfolio - CDC Data Exercise (Week 5)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Chaohua Li Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html">
 <span class="dropdown-text">Data Exercise (Week 4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">CDC Data Exercise (Week 5)</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CL-epicat/chaohuali-MADA-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CDC Data Exercise (Week 5)</h1>
<p class="subtitle lead">Vaccine Hesitancy for COVID-19: County and local estimates</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The dataset of “Vaccine Hesitancy for COVID-19: County and local estimates” from <a href="https://data.cdc.gov/" class="uri">https://data.cdc.gov/</a> was used for this exercise. This dataset contains estimates of percentage of adults who had vaccine hesitancy, Social Vulnerability Index, and percentages of different races for all US counties. Because the complete dataset is over 150MB, I queried and exported the data for only the counties in Georgia. Details of the data can be found <a href="#0" style="font-size: 11pt;">here</a>.</p>
<section id="load-packages-and-data" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-and-data">Load packages and data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load packages </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readr"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"here"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/sandi/MADA-course/chaohuali-MADA-portfolio</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Hmisc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ purrr     1.0.2
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::src()       masks Hmisc::src()
✖ dplyr::summarize() masks Hmisc::summarize()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"gtsummary"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"knitr"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#read csv data</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>vaccine <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"cdcdata-exercise"</span>, <span class="st">"Vaccine_Hesitancy_for_COVID-19__County_and_local_estimates_20240206.csv"</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#preview dataset</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(vaccine) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 159
Columns: 23
$ FIPS.Code                                                        &lt;int&gt; 13117…
$ County.Name                                                      &lt;chr&gt; "Fors…
$ State                                                            &lt;chr&gt; "GEOR…
$ Estimated.hesitant                                               &lt;dbl&gt; 0.104…
$ Estimated.hesitant.or.unsure                                     &lt;dbl&gt; 0.143…
$ Estimated.strongly.hesitant                                      &lt;dbl&gt; 0.065…
$ Social.Vulnerability.Index..SVI.                                 &lt;dbl&gt; 0.04,…
$ SVI.Category                                                     &lt;chr&gt; "Very…
$ CVAC.level.of.concern.for.vaccination.rollout                    &lt;dbl&gt; 0.44,…
$ CVAC.Level.Of.Concern                                            &lt;chr&gt; "Mode…
$ Percent.adults.fully.vaccinated.against.COVID.19..as.of.6.10.21. &lt;dbl&gt; 0.183…
$ Percent.Hispanic                                                 &lt;dbl&gt; 0.095…
$ Percent.non.Hispanic.American.Indian.Alaska.Native               &lt;dbl&gt; 0.001…
$ Percent.non.Hispanic.Asian                                       &lt;dbl&gt; 0.129…
$ Percent.non.Hispanic.Black                                       &lt;dbl&gt; 0.033…
$ Percent.non.Hispanic.Native.Hawaiian.Pacific.Islander            &lt;dbl&gt; 0.000…
$ Percent.non.Hispanic.White                                       &lt;dbl&gt; 0.717…
$ Geographical.Point                                               &lt;chr&gt; "POIN…
$ State.Code                                                       &lt;chr&gt; "GA",…
$ County.Boundary                                                  &lt;chr&gt; "MULT…
$ State.Boundary                                                   &lt;chr&gt; "MULT…
$ States                                                           &lt;int&gt; 31, 3…
$ Counties                                                         &lt;int&gt; 1611,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a new dataset that contains only the variables of interest</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>vaccine_2  <span class="ot">&lt;-</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  vaccine <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">SVI.Category=</span><span class="fu">factor</span>(SVI.Category) ) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">CVAC.Level.Of.Concern=</span><span class="fu">factor</span>(CVAC.Level.Of.Concern) ) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(FIPS.Code, Estimated.hesitant, Percent.Hispanic, Percent.non.Hispanic.Black, Percent.non.Hispanic.Asian, SVI.Category , CVAC.Level.Of.Concern)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we have created a new dataset which includes only the variables of interest.</p>
<p><em>FIPS.Code</em>: id for counties</p>
<p><em>Estimated.hesitant</em>: Estimate of percentage of adults who describe themselves as “probably not” or “definitely not” going to get a COVID-19 vaccine once one is available to them, based on national survey data</p>
<p><em>Percent.Hispanic:</em> Percent of county population that is Hispanic</p>
<p><em>Percent.non.Hispanic.Black:</em> Percent of county population that is non-Hispanic Black</p>
<p><em>Percent.non.Hispanic.Asian:</em> Percent of county population that is non-Hispanic Asian</p>
<p><em>SVI.Category</em>: SVI categorized as follows: Very Low (0.0-0.19), Low (0.20-0.39); Moderate (0.40-0.59); High (0.60-0.79); Very High (0.80-1.0)</p>
<p><em>CVAC.Level.Of.Concern</em>: CVAC categorized as follows: Very Low (0.0-0.19), Low (0.20-0.39); Moderate (0.40-0.59); High (0.60-0.79); Very High (0.80-1.0)</p>
</section>
<section id="explore-and-process-data" class="level2">
<h2 class="anchored" data-anchor-id="explore-and-process-data">Explore and process data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#inspect the summaries of the variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(vaccine_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>vaccine_2 

 7  Variables      159  Observations
--------------------------------------------------------------------------------
FIPS.Code 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1    13161      108    13017    13033 
     .25      .50      .75      .90      .95 
   13082    13161    13242    13289    13305 

lowest : 13001 13003 13005 13007 13009, highest: 13313 13315 13317 13319 13321
--------------------------------------------------------------------------------
Estimated.hesitant 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0       48    0.998   0.1618  0.01807   0.1363   0.1469 
     .25      .50      .75      .90      .95 
  0.1526   0.1623   0.1728   0.1864   0.1880 

lowest : 0.1049 0.1085 0.1136 0.1178 0.1195, highest: 0.1747 0.1767 0.1784 0.1864 0.188 
--------------------------------------------------------------------------------
Percent.Hispanic 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      152        1  0.06489  0.05317  0.00803  0.01796 
     .25      .50      .75      .90      .95 
 0.03040  0.05050  0.08090  0.11848  0.15842 

lowest : 0.0014 0.0028 0.0037 0.0043 0.0047, highest: 0.2117 0.2488 0.2728 0.2839 0.3511
--------------------------------------------------------------------------------
Percent.non.Hispanic.Black 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      158        1   0.2824   0.2014  0.01441  0.03316 
     .25      .50      .75      .90      .95 
 0.14530  0.27760  0.39820  0.52726  0.60390 

lowest : 0.0025 0.0041 0.0065 0.0074 0.0103, highest: 0.6239 0.624  0.6833 0.6939 0.7313
--------------------------------------------------------------------------------
Percent.non.Hispanic.Asian 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      113    0.999  0.01258  0.01464  0.00000  0.00060 
     .25      .50      .75      .90      .95 
 0.00325  0.00760  0.01355  0.03076  0.03923 

lowest : 0      1e-04  2e-04  7e-04  0.0013, highest: 0.0604 0.0703 0.0734 0.116  0.1291
--------------------------------------------------------------------------------
SVI.Category 
       n  missing distinct 
     159        0        5 

High Vulnerability (31, 0.195), Low Vulnerability (15, 0.094), Moderate
Vulnerability (21, 0.132), Very High Vulnerability (82, 0.516), Very Low
Vulnerability (10, 0.063)
--------------------------------------------------------------------------------
CVAC.Level.Of.Concern 
       n  missing distinct 
     159        0        5 
                                                                
Value           High Concern       Low Concern  Moderate Concern
Frequency                 50                 4                27
Proportion             0.314             0.025             0.170
                                              
Value      Very High Concern  Very Low Concern
Frequency                 77                 1
Proportion             0.484             0.006
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>From the results above, none of the variables have missing entries or unreasonable outliers. But we need to collapse some of the groups that have very small numbers for the two categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#collapse small groups for SVI.Category and CVAC.Level.Of.Concern </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>vaccine_2 <span class="ot">&lt;-</span> vaccine_2 <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SVI.Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    SVI.Category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Very Low Vulnerability"</span>, <span class="st">"Low Vulnerability"</span>) <span class="sc">~</span> <span class="st">"Low/Very Low"</span>,                            <span class="co"># combine Low and Very Low  </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> SVI.Category   )) <span class="sc">%&gt;%</span> <span class="co"># leave other categories unchanged</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">CVAC.Level.Of.Concern  =</span> <span class="fu">case_when</span>(</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    CVAC.Level.Of.Concern  <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Very Low Concern"</span>, <span class="st">"Low Concern"</span>, <span class="st">"Moderate Concern"</span>) <span class="sc">~</span> <span class="st">"Very Low/Low/Moderate"</span>,   <span class="co"># combine Very Low, Low and Moderate</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> CVAC.Level.Of.Concern       <span class="co"># leave other categories unchanged</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#check if recoding worked</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(vaccine_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>vaccine_2 

 7  Variables      159  Observations
--------------------------------------------------------------------------------
FIPS.Code 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1    13161      108    13017    13033 
     .25      .50      .75      .90      .95 
   13082    13161    13242    13289    13305 

lowest : 13001 13003 13005 13007 13009, highest: 13313 13315 13317 13319 13321
--------------------------------------------------------------------------------
Estimated.hesitant 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0       48    0.998   0.1618  0.01807   0.1363   0.1469 
     .25      .50      .75      .90      .95 
  0.1526   0.1623   0.1728   0.1864   0.1880 

lowest : 0.1049 0.1085 0.1136 0.1178 0.1195, highest: 0.1747 0.1767 0.1784 0.1864 0.188 
--------------------------------------------------------------------------------
Percent.Hispanic 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      152        1  0.06489  0.05317  0.00803  0.01796 
     .25      .50      .75      .90      .95 
 0.03040  0.05050  0.08090  0.11848  0.15842 

lowest : 0.0014 0.0028 0.0037 0.0043 0.0047, highest: 0.2117 0.2488 0.2728 0.2839 0.3511
--------------------------------------------------------------------------------
Percent.non.Hispanic.Black 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      158        1   0.2824   0.2014  0.01441  0.03316 
     .25      .50      .75      .90      .95 
 0.14530  0.27760  0.39820  0.52726  0.60390 

lowest : 0.0025 0.0041 0.0065 0.0074 0.0103, highest: 0.6239 0.624  0.6833 0.6939 0.7313
--------------------------------------------------------------------------------
Percent.non.Hispanic.Asian 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      113    0.999  0.01258  0.01464  0.00000  0.00060 
     .25      .50      .75      .90      .95 
 0.00325  0.00760  0.01355  0.03076  0.03923 

lowest : 0      1e-04  2e-04  7e-04  0.0013, highest: 0.0604 0.0703 0.0734 0.116  0.1291
--------------------------------------------------------------------------------
SVI.Category 
       n  missing distinct 
     159        0        4 
                                                          
Value           High Vulnerability            Low/Very Low
Frequency                       31                      25
Proportion                   0.195                   0.157
                                                          
Value       Moderate Vulnerability Very High Vulnerability
Frequency                       21                      82
Proportion                   0.132                   0.516
--------------------------------------------------------------------------------
CVAC.Level.Of.Concern 
       n  missing distinct 
     159        0        3 
                                                                            
Value               High Concern     Very High Concern Very Low/Low/Moderate
Frequency                     50                    77                    32
Proportion                 0.314                 0.484                 0.201
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Now, SVI.Category has 4 categories and CVAC.Level.Of.Concern has 3 categories. The dataset is ready for analysis.</p>
</section>
<section id="table-and-figures-showing-distribution-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="table-and-figures-showing-distribution-of-variables">Table and figures showing distribution of variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get descriptive statistics of variables and create a table</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ab<span class="ot">&lt;-</span>gtsummary<span class="sc">::</span><span class="fu">tbl_summary</span>(<span class="fu">select</span>(vaccine_2,<span class="sc">-</span><span class="st">"FIPS.Code"</span>), <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean}/{sd}"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">"{n} / {N} ({p}%)"</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>),)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ab,<span class="at">caption =</span> <span class="st">"Summary Table: Mean/SD or n/N(%)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Summary Table: Mean/SD or n/N(%)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 159</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Estimated.hesitant</td>
<td style="text-align: left;">0.162/0.016</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent.Hispanic</td>
<td style="text-align: left;">0.06/0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Percent.non.Hispanic.Black</td>
<td style="text-align: left;">0.28/0.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent.non.Hispanic.Asian</td>
<td style="text-align: left;">0.013/0.018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SVI.Category</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">High Vulnerability</td>
<td style="text-align: left;">31 / 159 (19%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low/Very Low</td>
<td style="text-align: left;">25 / 159 (16%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate Vulnerability</td>
<td style="text-align: left;">21 / 159 (13%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very High Vulnerability</td>
<td style="text-align: left;">82 / 159 (52%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">CVAC.Level.Of.Concern</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">High Concern</td>
<td style="text-align: left;">50 / 159 (31%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very High Concern</td>
<td style="text-align: left;">77 / 159 (48%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very Low/Low/Moderate</td>
<td style="text-align: left;">32 / 159 (20%)</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Estimated.hesitant</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2<span class="sc">$</span>Estimated.hesitant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.Hispanic</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2<span class="sc">$</span>Percent.Hispanic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.non.Hispanic.Black</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2<span class="sc">$</span>Percent.non.Hispanic.Black)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.non.Hispanic.Asian</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2<span class="sc">$</span>Percent.non.Hispanic.Asian   )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the histograms, we know none of the four continuous variables have normal distribution.</p>
</section>
<section id="this-section-contributed-by-patrick-kaggwa" class="level2">
<h2 class="anchored" data-anchor-id="this-section-contributed-by-patrick-kaggwa">This section contributed by Patrick Kaggwa</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Looking at the columns of vaccine2 before creating a synthetic dataset </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vaccine_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "FIPS.Code"                  "Estimated.hesitant"        
[3] "Percent.Hispanic"           "Percent.non.Hispanic.Black"
[5] "Percent.non.Hispanic.Asian" "SVI.Category"              
[7] "CVAC.Level.Of.Concern"     </code></pre>
</div>
</div>
<p>After undertanding the description of the above dataframe, I used ChatGPT to create a new dataframe called vaccine_2pk with the same structure as vaccine_2.</p>
<section id="chatgpt-prompt" class="level3">
<h3 class="anchored" data-anchor-id="chatgpt-prompt">ChatGPT prompt</h3>
<p>Create a dataset that should consist of 159 observations and include the following variables: FIPS codes, Estimated hesitant values, Percent Hispanic values, Percent non-Hispanic Black values, Percent non-Hispanic Asian values, SVI Category, and CVAC Level of Concern. To ensure reproducibility, set the seed to 123 before generating random values. The FIPS codes should range from 13001 to 13159. The Estimated hesitant values should be uniformly distributed between 0.1049 and 0.188. Percent Hispanic values should range uniformly between 0.0014 and 0.3511. Percent non-Hispanic Black values should range uniformly between 0.0025 and 0.7313. Percent non-Hispanic Asian values should range uniformly between 0 and 0.1291. The SVI Category should be sampled with replacement from ‘High Vulnerability’, ‘Low/Very Low’, ‘Moderate Vulnerability’, and ‘Very High Vulnerability’, with probabilities of 31/159, 25/159, 21/159, and 82/159 respectively. Similarly, the CVAC Level of Concern should be sampled with replacement from ‘High Concern’, ‘Very High Concern’, and ‘Very Low/Low/Moderate’, with probabilities of 50/159, 77/159, and 32/159 respectively. Create a dataframe with these variables named ’vaccine_2pk.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate FIPS codes</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>FIPS.Code <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">13001</span>, <span class="dv">13159</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate Estimated hesitant values</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>Estimated.hesitant <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">159</span>, <span class="at">min =</span> <span class="fl">0.1049</span>, <span class="at">max =</span> <span class="fl">0.188</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate Percent Hispanic values</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>Percent.Hispanic <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">159</span>, <span class="at">min =</span> <span class="fl">0.0014</span>, <span class="at">max =</span> <span class="fl">0.3511</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate Percent non-Hispanic Black values</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>Percent.non.Hispanic.Black <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">159</span>, <span class="at">min =</span> <span class="fl">0.0025</span>, <span class="at">max =</span> <span class="fl">0.7313</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate Percent non-Hispanic Asian values</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>Percent.non.Hispanic.Asian <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">159</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="fl">0.1291</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate SVI Category with exact distribution</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>SVI.Category <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"High Vulnerability"</span>, <span class="st">"Low/Very Low"</span>, <span class="st">"Moderate Vulnerability"</span>, <span class="st">"Very High Vulnerability"</span>),</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">159</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">31</span><span class="sc">/</span><span class="dv">159</span>, <span class="dv">25</span><span class="sc">/</span><span class="dv">159</span>, <span class="dv">21</span><span class="sc">/</span><span class="dv">159</span>, <span class="dv">82</span><span class="sc">/</span><span class="dv">159</span>))</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate CVAC Level of Concern</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>CVAC.Level.Of.Concern <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"High Concern"</span>, <span class="st">"Very High Concern"</span>, <span class="st">"Very Low/Low/Moderate"</span>),</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>                                <span class="dv">159</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">50</span><span class="sc">/</span><span class="dv">159</span>, <span class="dv">77</span><span class="sc">/</span><span class="dv">159</span>, <span class="dv">32</span><span class="sc">/</span><span class="dv">159</span>))</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dataframe</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>vaccine_2pk <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">FIPS.Code =</span> FIPS.Code,</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimated.hesitant =</span> Estimated.hesitant,</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percent.Hispanic =</span> Percent.Hispanic,</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percent.non.Hispanic.Black =</span> Percent.non.Hispanic.Black,</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">Percent.non.Hispanic.Asian =</span> Percent.non.Hispanic.Asian,</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">SVI.Category =</span> SVI.Category,</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">CVAC.Level.Of.Concern =</span> CVAC.Level.Of.Concern</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary statistics for each variable</span></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vaccine_2pk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   FIPS.Code     Estimated.hesitant Percent.Hispanic  
 Min.   :13001   Min.   :0.1050     Min.   :0.003603  
 1st Qu.:13040   1st Qu.:0.1253     1st Qu.:0.094079  
 Median :13080   Median :0.1437     Median :0.169970  
 Mean   :13080   Mean   :0.1464     Mean   :0.174977  
 3rd Qu.:13120   3rd Qu.:0.1668     3rd Qu.:0.255824  
 Max.   :13159   Max.   :0.1875     Max.   :0.346079  
 Percent.non.Hispanic.Black Percent.non.Hispanic.Asian SVI.Category      
 Min.   :0.01545            Min.   :6.008e-05          Length:159        
 1st Qu.:0.17746            1st Qu.:3.539e-02          Class :character  
 Median :0.33418            Median :6.698e-02          Mode  :character  
 Mean   :0.36120            Mean   :6.590e-02                            
 3rd Qu.:0.53799            3rd Qu.:1.034e-01                            
 Max.   :0.73087            Max.   :1.282e-01                            
 CVAC.Level.Of.Concern
 Length:159           
 Class :character     
 Mode  :character     
                      
                      
                      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I will desecribe the da</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(vaccine_2pk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>vaccine_2pk 

 7  Variables      159  Observations
--------------------------------------------------------------------------------
FIPS.Code 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1    13080    53.33    13009    13017 
     .25      .50      .75      .90      .95 
   13040    13080    13120    13143    13151 

lowest : 13001 13002 13003 13004 13005, highest: 13155 13156 13157 13158 13159
--------------------------------------------------------------------------------
Estimated.hesitant 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1   0.1464   0.0273   0.1123   0.1154 
     .25      .50      .75      .90      .95 
  0.1253   0.1437   0.1668   0.1791   0.1842 

lowest : 0.104952 0.10577  0.106945 0.108395 0.108686
highest: 0.184927 0.186323 0.186689 0.18675  0.187524
--------------------------------------------------------------------------------
Percent.Hispanic 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1    0.175   0.1124  0.02158  0.03743 
     .25      .50      .75      .90      .95 
 0.09408  0.16997  0.25582  0.30924  0.32963 

lowest : 0.00360338 0.00427297 0.00469764 0.0084025  0.018068  
highest: 0.339699   0.340384   0.341265   0.344854   0.346079  
--------------------------------------------------------------------------------
Percent.non.Hispanic.Black 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1   0.3612   0.2407  0.07465  0.10029 
     .25      .50      .75      .90      .95 
 0.17746  0.33418  0.53799  0.66356  0.71305 

lowest : 0.0154477 0.022901  0.0270808 0.0279168 0.0449102
highest: 0.721063  0.721136  0.724913  0.728835  0.730866 
--------------------------------------------------------------------------------
Percent.non.Hispanic.Asian 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     159        0      159        1   0.0659  0.04522 0.005402 0.010479 
     .25      .50      .75      .90      .95 
0.035393 0.066978 0.103433 0.115688 0.122780 

lowest : 6.00766e-05 0.00208632  0.0023708   0.00283939  0.0032955  
highest: 0.12618     0.126415    0.12769     0.128189    0.128202   
--------------------------------------------------------------------------------
SVI.Category 
       n  missing distinct 
     159        0        4 
                                                          
Value           High Vulnerability            Low/Very Low
Frequency                       32                      30
Proportion                   0.201                   0.189
                                                          
Value       Moderate Vulnerability Very High Vulnerability
Frequency                       18                      79
Proportion                   0.113                   0.497
--------------------------------------------------------------------------------
CVAC.Level.Of.Concern 
       n  missing distinct 
     159        0        3 
                                                                            
Value               High Concern     Very High Concern Very Low/Low/Moderate
Frequency                     57                    75                    27
Proportion                 0.358                 0.472                 0.170
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get descriptive statistics of variables and create a table</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>ab<span class="ot">&lt;-</span>gtsummary<span class="sc">::</span><span class="fu">tbl_summary</span>(<span class="fu">select</span>(vaccine_2pk,<span class="sc">-</span><span class="st">"FIPS.Code"</span>), <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean}/{sd}"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">"{n} / {N} ({p}%)"</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>),)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ab,<span class="at">caption =</span> <span class="st">"Summary Table: Mean/SD or n/N(%)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Summary Table: Mean/SD or n/N(%)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 159</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Estimated.hesitant</td>
<td style="text-align: left;">0.146/0.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent.Hispanic</td>
<td style="text-align: left;">0.17/0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Percent.non.Hispanic.Black</td>
<td style="text-align: left;">0.36/0.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent.non.Hispanic.Asian</td>
<td style="text-align: left;">0.07/0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SVI.Category</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">High Vulnerability</td>
<td style="text-align: left;">32 / 159 (20%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low/Very Low</td>
<td style="text-align: left;">30 / 159 (19%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate Vulnerability</td>
<td style="text-align: left;">18 / 159 (11%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very High Vulnerability</td>
<td style="text-align: left;">79 / 159 (50%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">CVAC.Level.Of.Concern</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">High Concern</td>
<td style="text-align: left;">57 / 159 (36%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very High Concern</td>
<td style="text-align: left;">75 / 159 (47%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Very Low/Low/Moderate</td>
<td style="text-align: left;">27 / 159 (17%)</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Estimated.hesitant</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2pk<span class="sc">$</span>Estimated.hesitant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.Hispanic</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2pk<span class="sc">$</span>Percent.Hispanic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.non.Hispanic.Black</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2pk<span class="sc">$</span>Percent.non.Hispanic.Black)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of Percent.non.Hispanic.Asian</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(vaccine_2pk<span class="sc">$</span>Percent.non.Hispanic.Asian )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histograms show less skewed but at the same time they are not normally distributed. This is consistent with the histograms using dataframe vaccine_2</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>